20221124-004839
0.10336422920227051
898509
Traceback (most recent call last):
  File "prun_train/prune.py", line 243, in <module>
    main(exp,args)
  File "prun_train/prune.py", line 209, in main
    loose_model, prune_mask_dict, prune_bn_dict, mask_bn_channel_dict)
  File "prun_train/prune.py", line 92, in init_weights_from_loose_model
    pruned_model = yolox_prun(mask_bn_channel_dict)
  File "/data/happyhoo97/repos/YOLOX/prun_train/prune_model.py", line 627, in __init__
    backbone = YOLOPAFPN_prune(mask_bn_channel_dict=mask_bn_channel_dict)
  File "/data/happyhoo97/repos/YOLOX/prun_train/prune_model.py", line 427, in __init__
    bu_conv1_out = mask_bn_channel_dict["backbone.bu_conv1.bn"]
KeyError: 'backbone.bu_conv1.bn'
done
