20221125-132927
0.1092226505279541
898509
Case 1
=== in_idx ===
Traceback (most recent call last):
  File "prun_train/prune.py", line 257, in <module>
    main(exp,args)
  File "prun_train/prune.py", line 223, in main
    loose_model, prune_mask_dict, prune_bn_dict, mask_bn_channel_dict)
  File "prun_train/prune.py", line 141, in init_weights_from_loose_model
    print(in_idxtems)
NameError: name 'in_idxtems' is not defined
done
